remote_theme: "mmistakes/minimal-mistakes@4.22.0"
title: Johan Hellmark
subtitle: A portfolio.
# logo: assets/img/businessman-310819_1280.png
description: # "Contact me at: <br /> Johan.hellmark50@gmail.com"
url: "https://hellmarkjohan.github.io/"
baseurl: ""
repository: "HellmarkJohan/hellmarkJohan.github.io"
include: 
  - _pages

plugins:
  - jekyll-include-cache
  
author:
  name: "Johan Hellmark "
  avatar: "/assets/images/profile_pic.jpeg"
  bio: "A driven engineer combining software, mathematics and management." # Note: Markdown is allowed
  location: "Lund/Malm√∂, Sweden"
  links:
    - label: " Linkedin"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/johan-hellmark-689236206/"
    - label: " Email"
      icon: "far fa-envelope"
      url: "mailto:johan.hellmark50@gmail.com"


